#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
mkdir /var/www/html/redirect_me
touch /var/www/html/redirect_me/index.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
