#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
mkdir /var/www/html/redirect_me
touch /var/www/html/redirect_me/index.html

replaced="server_name _;"
new_string="${replaced}\n\n\tlocation = /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sed -i "s|$replaced|$new_string|" /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
error_404="${replaced}\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "s|$replaced|$error_404|" /etc/nginx/sites-available/default
