#!/usr/bin/env bash
# 0. Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default

sudo sed -i '/^}$/i \ \n\terror_page 404 = @redirect;' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\rlocation @redirect {\n\t\treturn 404 "Ceci n'\''est pas une page";\n\t}' /etc/nginx/sites-available/default
hostname=$(hostname)
sudo sed -i "/^}$/i \ \n\tadd_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo systemctl reload nginx
