#!/usr/bin/env bash
# 1. Install your load balancer

sudo apt update
sudo apt-get -y install haproxy

sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.162.104.87:80 check\n\tserver server2 3.90.84.83:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
